//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SudokuParaTodos.RecursosLocalizables {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SudokuParaTodos.RecursosLocalizables.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abrir Juego.
        /// </summary>
        internal static string btnAbrir {
            get {
                return ResourceManager.GetString("btnAbrir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar Juego.
        /// </summary>
        internal static string btnGuardar {
            get {
                return ResourceManager.GetString("btnGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Otro Juego.
        /// </summary>
        internal static string btnOtro {
            get {
                return ResourceManager.GetString("btnOtro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar Solucion.
        /// </summary>
        internal static string btnSolucion {
            get {
                return ResourceManager.GetString("btnSolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sudoku Para Todos.
        /// </summary>
        internal static string Form1 {
            get {
                return ResourceManager.GetString("Form1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ARCHIVO.
        /// </summary>
        internal static string mArchivo {
            get {
                return ResourceManager.GetString("mArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a COLORES.
        /// </summary>
        internal static string mColores {
            get {
                return ResourceManager.GetString("mColores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CONTADORES.
        /// </summary>
        internal static string mContadores {
            get {
                return ResourceManager.GetString("mContadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IDIOMAS .
        /// </summary>
        internal static string mIdiomas {
            get {
                return ResourceManager.GetString("mIdiomas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        internal static string mIEspañol {
            get {
                return ResourceManager.GetString("mIEspañol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingles.
        /// </summary>
        internal static string mIIngles {
            get {
                return ResourceManager.GetString("mIIngles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Portugues.
        /// </summary>
        internal static string mIPortugues {
            get {
                return ResourceManager.GetString("mIPortugues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TABLERO.
        /// </summary>
        internal static string mTablero {
            get {
                return ResourceManager.GetString("mTablero", resourceCulture);
            }
        }
    }
}
